### ISSUE TITLE
Pay Fabric API/ Create Transaction

### ISSUE THREAD

**Issue by Nabeel164** [PayFabric/Hosted-Pages#1]
When i create transaction (TrxKey)  It's reponse give me null content in Asp.net.
My DeviceID|Password is also valid... Help please ?

var client = new RestClient("https://sandbox.payfabric.com/v2/rest/api/transaction/create");var request = new RestRequest(Method.POST);request.AddHeader("authorization", "DeviceID\|DevicePassword");request.AddHeader("content-type", "application/json");request.AddParameter("application/json", "{    "SetupId" : "PFP",    "Type" : "Sale",    "Customer" : "PayFabric",    "Amount" : 19.99,    "Currency" : "USD",    "Card" : {        "Account" : "4111111111111111",        "ExpDate": "0819",        "CardHolder" : {            "FirstName" : "John",            "LastName" : "Doe"        }    }}", ParameterType.RequestBody);IRestResponse response = client.Execute(request);

**Comment by ShaunSharples** [comment]
Hi @Nabeel164 , I assume because you close this that you managed to resolve this yourself?  Please let us know if you are still experiencing issues.

Regards,

Shaun
